suppressPackageStartupMessages({library(readr);library(stringr);library(dplyr);library(purrr);library(tidyr)})
cmd_args<-commandArgs(trailingOnly=FALSE);file_arg<-grep("^--file=",cmd_args,value=TRUE);script_path<-normalizePath(sub("^--file=","",file_arg));setwd(dirname(dirname(script_path)))
model_file<-"model/ajan_alas_species_model.R";if(!file.exists(model_file))stop("Missing ",model_file);source(model_file)
bpp<-Sys.getenv("BPP_BIN",unset="bpp");keep_trees<-tolower(Sys.getenv("KEEP_TREES",unset="false"))%in%c("1","true","yes","y")
if(!dir.exists("controls")){status<-system2("Rscript","scripts/generate_controls.R");if(status!=0)stop("Control generation failed")}
gdi_from_gtree<-function(fin,focal_population,tau){lines<-read_lines(fin,progress=FALSE)|>str_replace_all("\\^[A-Za-z0-9_]+","");number<-"[0-9.eE+-]+";pattern<-paste0("\\(",focal_population,":(",number,"),",focal_population,":(",number,")\\)");m<-str_match(lines,pattern);t1<-suppressWarnings(as.numeric(m[,2]));t2<-suppressWarnings(as.numeric(m[,3]));cherry<-!is.na(t1);if(any(cherry&abs(t1-t2)>1e-10,na.rm=TRUE))stop("Unequal focal terminal branches: ",fin);success<-cherry&t1<tau;tibble(n_gene_trees=length(lines),n_focal_pair_first=sum(cherry),n_focal_pair_first_before_tau=sum(success),gdi=sum(success)/length(lines))}
extract_tau<-function(ctl,node){txt<-paste(read_lines(ctl),collapse=" ");x<-str_match(txt,paste0(node,":([0-9.eE+-]+)"))[,2];if(is.na(x))stop("Missing tau node ",node);as.numeric(x)}
run_one<-function(chrom,comparison,config,pop_a,pop_b,focal_population,tau_node){ctl<-file.path("controls",paste0(chrom,"_",comparison,"_",config,".ctl"));tree<-file.path("output","trees",paste0(chrom,"_",comparison,"_",config,".tree.txt"));dir.create(dirname(tree),recursive=TRUE,showWarnings=FALSE);if(file.exists(tree))unlink(tree);tau<-extract_tau(ctl,tau_node);message("Running ",chrom," ",comparison," ",config);status<-system2(bpp,c("--quiet","--simulate",ctl));if(status!=0)stop("BPP failed");score<-gdi_from_gtree(tree,focal_population,tau);if(!keep_trees)unlink(tree);tibble(chromosome=chrom,comparison=comparison,configuration=config,focal_population=focal_population,tau_node=tau_node,tau=tau)|>bind_cols(score)}
chromosomes<-paste0("ch",1:9);raw<-map_dfr(chromosomes,function(chrom)pmap_dfr(comparison_specs,function(comparison,config,pop_a,pop_b,focal_population,tau_node)run_one(chrom,comparison,config,pop_a,pop_b,focal_population,tau_node)));dir.create("output",showWarnings=FALSE);write_csv(raw,"output/gdi_ajan_alas_long.csv");wide<-raw|>mutate(column=paste0("gdi_",comparison,"__",focal_population))|>select(chromosome,column,gdi)|>pivot_wider(names_from=column,values_from=gdi);write_csv(wide,"output/gdi_ajan_alas.csv");print(wide)
